spring:
  profiles:
    #include: oauth
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/clothes_mall?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver
    #url: jdbc:h2:~/data/data
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug
